CUDA_VISIBLE_DEVICES=$1 python3 -u src/myrun.py \
    --file_dir data/mmkb-datasets/$3 \
    --rate $4 \
    --lr .0005 \
    --epochs 1000 \
    --hidden_units "300,300,300" \
    --check_point 50 \
    --bsize 512 \
    --semi_learn_step 5 \
    --csls \
    --csls_k 3 \
    --seed $2 \
    --tau 0.1 \
    --tau2 4.0 \
    --structure_encoder "gat" \
    --img_dim 300 \
    --attr_dim 300 \
    --w_name \
    --w_char \
    --save_path "save_pkl/${3}_noniter_${4}"